language: php

env:
  - IMAGINE_DRIVER=imagick
  - IMAGINE_DRIVER=gmagick

before_script:
  - sh -c " if [ '$IMAGINE_DRIVER' = 'imagick' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm-nightly' ]; then
              wget http://www.imagemagick.org/download/legacy/ImageMagick-6.8.5-10.tar.gz;
            fi"
  - sh -c " if [ '$IMAGINE_DRIVER' = 'gmagick' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm' ] && [ '$TRAVIS_PHP_VERSION' != 'hhvm-nightly' ]; then
              wget http://pecl.php.net/get/gmagick-1.1.0RC3.tgz;
            fi"

php:
  - 5.5
  - hhvm
  - hhvm-nightly
